# Generated by Django 3.1.13 on 2021-12-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_presupuesto',
            name='Ejecutado',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line_presupuesto',
            name='En_Ejucucion',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line_presupuesto',
            name='Saldo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line_presupuesto',
            name='Total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
