# Generated by Django 3.1.13 on 2021-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20211209_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='line_presupuesto',
            name='Proyecto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cronogram',
            name='Proyecto',
            field=models.CharField(max_length=150),
        ),
    ]
