# Generated by Django 3.1.13 on 2021-12-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20211209_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Proyecto',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
