# Generated by Django 3.1.13 on 2021-12-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_event_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Presupuesto',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
