# Generated by Django 3.1.13 on 2021-12-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_event_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='Aprobacion',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='Comentario',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
